on:
  schedule:
    - cron: "0 5 * * *"


jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update local files
        run: ./count_qupath_downloads.sh > "download-stats/$(date -I | sed -e 's/ /-/g').txt"

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "Add download stats"
          git push
