name: Update download stats

on:
  schedule:
    - cron: "0 5 * * *"
  push:

jobs:
  execute:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4

      - name: Check download stats
        run: |
          mkdir -p download-stats
          ./count_qupath_downloads.sh > "download-stats/$(date -I | sed -e 's/ /-/g').txt"

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty -am "Add download stats"
          git push
