name: Java CI with Gradle

on:
  workflow_call:
    inputs:
      build-tool:
        description: The build tool to use
        default: ./gradlew
        required: false
        type: string
      java-version:
        description: The java version used for setup-java
        default: 21
        required: false
        type: string
      java-distribution:
        description: The JDK distribution
        default: temurin
        required: false
        type: string
      artifact-name:
        description: The artifact name for upload
        default: ${{ github.event.repository.name }}
        required: false
        type: string
      artifact-path:
        description: Where to find the artifacts for upload
        required: false
        default: build/libs/*.jar
        type: string
      gradle-args:
        description: The command and arguments to run with gradle
        type: string
        default: build
        required: false

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ${{ inputs.build-tool }} ${{ inputs.gradle-args }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
          retention-days: 7
