name: Update gradle versions

on:
  workflow_dispatch:
    inputs:
      gradle-version:
        description: Gradle version
        default: latest
        type: string
        required: false

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        repository:
          - c-blosc-jars
          - extension-manager
          - javadoc-viewer
          - log-viewer
          - openslide-jars
          - script-editor
          - qupath
          - qupath-fxtras
          - qupath-gradle-scripting-project
          - qupath-gradle-plugin
          - qupath-bioimageio-spec
          - qupath-extension-appose
          - qupath-extension-align
          - qupath-extension-djl
          - qupath-extension-instanseg
          - qupath-extension-jpen
          - qupath-extension-liverquant
          - qupath-extension-omero
          - qupath-extension-py4j
          - qupath-extension-stitching
          - qupath-extension-snapshots
          - qupath-extension-stardist
          - qupath-extension-template
          - qupath-extension-training
          - qupath-extension-wsinfer
          - qupath-extension-scripting
    steps:
      - uses: actions/checkout@v4
        with:
         token: ${{ secrets.BADGES_ACCESS_TOKEN }}
         repository: qupath/${{ matrix.repository }}
      - name: Update gradlew
        run: |
          ./gradlew wrapper --gradle-version ${{ inputs.gradle-version }}
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty -m "Update gradle via qupath/actions/.github/workflows/update-gradle.yml"
          git push
